parameters:
  database_driver: pdo_sqlsrv
  database_host: DESKTOP-I516SA9\SQLEXPRESS
  database_port: null
  database_name: BTG_DOS_BATOEI
  database_user: kebsibadr
  database_password: Saiko123
  database_charset: UTF-8


doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: "%database_driver%"
        charset:  "%database_charset%"
        host: "%database_host%"
        port:     "%database_port%"
        user: "%database_user%"
        password: "%database_password%"
        dbname: "%database_name%"
        options:
           Encrypt: true
           TrustServerCertificate: true


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
