controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

calendar_events:
    path: /calendar/events
    controller: App\Controller\CalendarController::getCalendarEvents
