controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /bato_apps/index
    controller: App\Controller\BatoAppsController::index